 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/inactive_events", type: :request do
  # InactiveEvent. As you add validations to InactiveEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      InactiveEvent.create! valid_attributes
      get inactive_events_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      inactive_event = InactiveEvent.create! valid_attributes
      get inactive_event_url(inactive_event)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_inactive_event_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      inactive_event = InactiveEvent.create! valid_attributes
      get edit_inactive_event_url(inactive_event)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new InactiveEvent" do
        expect {
          post inactive_events_url, params: { inactive_event: valid_attributes }
        }.to change(InactiveEvent, :count).by(1)
      end

      it "redirects to the created inactive_event" do
        post inactive_events_url, params: { inactive_event: valid_attributes }
        expect(response).to redirect_to(inactive_event_url(InactiveEvent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new InactiveEvent" do
        expect {
          post inactive_events_url, params: { inactive_event: invalid_attributes }
        }.to change(InactiveEvent, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post inactive_events_url, params: { inactive_event: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested inactive_event" do
        inactive_event = InactiveEvent.create! valid_attributes
        patch inactive_event_url(inactive_event), params: { inactive_event: new_attributes }
        inactive_event.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the inactive_event" do
        inactive_event = InactiveEvent.create! valid_attributes
        patch inactive_event_url(inactive_event), params: { inactive_event: new_attributes }
        inactive_event.reload
        expect(response).to redirect_to(inactive_event_url(inactive_event))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        inactive_event = InactiveEvent.create! valid_attributes
        patch inactive_event_url(inactive_event), params: { inactive_event: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested inactive_event" do
      inactive_event = InactiveEvent.create! valid_attributes
      expect {
        delete inactive_event_url(inactive_event)
      }.to change(InactiveEvent, :count).by(-1)
    end

    it "redirects to the inactive_events list" do
      inactive_event = InactiveEvent.create! valid_attributes
      delete inactive_event_url(inactive_event)
      expect(response).to redirect_to(inactive_events_url)
    end
  end
end
